bpf: Fix agent crash when dumping map events
The underlying ringbuffer here is not thread-safe, so access into the
buffer needs to be single-threaded. Prior to this patch, the event
generation, event consumption, and garbage collection codepaths could
each independently execute all at once because there was no mutex
protecting them. The dump path attempted to protect these paths through
acquiring a _read lock_ from the parent map, but this is insufficient to
prevent multiple goroutines from invoking the underlying ringbuffer
data concurrently.

The test in the following commit would fail prior to the fix:

    $ go test ./pkg/bpf/
    --- FAIL: TestEventsGC (0.00s)
    panic: runtime error: integer divide by zero [recovered, repanicked]

    goroutine 42 [running]:
    testing.tRunner.func1.2({0x17451c0, 0x2a19720})
            /home/joenats/sdk/go1.26.4/src/testing/testing.go:1974 +0x232
    testing.tRunner.func1()
            /home/joenats/sdk/go1.26.4/src/testing/testing.go:1977 +0x349
    panic({0x17451c0?, 0x2a19720?})
            /home/joenats/sdk/go1.26.4/src/runtime/panic.go:860 +0x13a
    github.com/cilium/cilium/pkg/container.(*RingBuffer[...]).mapIndex(...)
            /var/git/cilium/pkg/container/ring_buffer.go:83
    github.com/cilium/cilium/pkg/container.(*RingBuffer[...]).IterateValid(0x10, 0x27791e915df0?, 0x27791e915de0)
            /var/git/cilium/pkg/container/ring_buffer.go:76 +0x27f
    github.com/cilium/cilium/pkg/bpf.(*eventsBuffer).dumpWithCallback(0x27791e915e38?, 0x428005?)
            /var/git/cilium/pkg/bpf/events.go:179 +0x4a
    github.com/cilium/cilium/pkg/bpf.(*eventsBuffer).dumpAndSubscribe(0x27791ed908c0, {0x1b10920, 0x27791ed8e8c0}, 0x27791ed82da0, 0x0)
            /var/git/cilium/pkg/bpf/events.go:141 +0x33
    github.com/cilium/cilium/pkg/bpf.TestEventsGC(0x27791edc4b48)
            /var/git/cilium/pkg/bpf/events_test.go:64 +0x29c
    testing.tRunner(0x27791edc4b48, 0x1ae8168)
            /home/joenats/sdk/go1.26.4/src/testing/testing.go:2036 +0xea
    created by testing.(*T).Run in goroutine 1
            /home/joenats/sdk/go1.26.4/src/testing/testing.go:2101 +0x4c5
    FAIL    github.com/cilium/cilium/pkg/bpf        0.018s
    FAIL

Adding a new lock here seemed like the simpler option than attempting to
reuse the parent map's RWMutex, so I went with this option.

Thanks to Mike for identifying and reporting this bug.

Reported-by: Mike Molchanov <mikier@google.com>
Signed-off-by: Joe Stringer <joe@cilium.io>